## Import libraires

In [ ]:
import torch
import transformers
from huggingface_hub import notebook_login
import pandas as pd

transformers.__version__

'4.57.3'

In [ ]:
notebook_login()

In [ ]:
# !pip install datasets

----------------------------------------------------------------------
----------------------------------------------------------------------
----------------------------------------------------------------------



In [ ]:
from transformers import AutoModelForCausalLM
from transformers import AutoTokenizer

## Generating Text

In [ ]:
from transformers import AutoTokenizer

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("gpt2")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [ ]:
sentence = "unsure"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[13271,   495]])

In [ ]:
tokenizer.decode(input_ids[0])

'unsure'

In [ ]:
sentence = "unbelivable"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[  403,  6667, 21911]])

In [ ]:
tokenizer.decode(input_ids[0])

'unbelivable'

In [ ]:
sentence = "homoscedasticity"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[26452,   418,   771,  3477,   414]])

`words -> Tokens -> Unique ID -> Vector Embed`

In [ ]:
tokenizer.decode(torch.tensor([26452, 418, 771, 3477, 414]))

'homoscedasticity'

In [ ]:
sentence = "pneumonoultramicroscopicsilicovolcanoconiosis"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[   79, 25668,   261, 25955,   859,  2500,  1416,   404,   873, 41896,
           709,   349,  5171, 36221, 42960]])

In [ ]:
for token_id in input_ids[0]:
    print(tokenizer.decode(token_id))

p
neum
on
oult
ram
icro
sc
op
ics
ilic
ov
ol
can
ocon
iosis


In [ ]:
tokenizer.decode(torch.tensor([ 79, 25668,   261, 25955,   859,  2500,  1416,   404,   873, 41896,
           709,   349,  5171, 36221, 42960]))

'pneumonoultramicroscopicsilicovolcanoconiosis'

In [ ]:
sentence = "antidisestablishmentarianism"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[  415, 29207, 44390,  3699,  1042]])

In [ ]:
tokenizer.decode(torch.tensor([415, 29207, 44390,  3699,  1042]))

'antidisestablishmentarianism'

In [ ]:
sentence = "floccinaucinihilipilification"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[ 2704, 13966,   259, 14272,   259, 20898,   541,   346,  2649]])

In [ ]:
tokenizer.decode(torch.tensor([2704, 13966,   259, 14272,   259, 20898,   541,   346,  2649]))

'floccinaucinihilipilification'

In [ ]:
tokenizer.decode([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

'!"#$%&\'()*+'

In [ ]:
tokenizer.decode([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

',-./0123456789:'

In [ ]:
tokenizer.decode([26, 27, 28, 29, 30, 32, 33])

';<=>?AB'

In [ ]:
tokenizer.decode([100, 101, 1000, 1001])

'��ale Se'

In [ ]:
tokenizer.decode([60, 61, 70, 71])

']^gh'

In [ ]:
tokenizer.decode([202])

'\x0e'

In [ ]:
sentence = "I skip across the"
input_ids = tokenizer(sentence, return_tensors="pt").input_ids
input_ids

tensor([[   40, 14267,  1973,   262]])

In [ ]:
from transformers import AutoModelForCausalLM

In [ ]:
gpt2 = AutoModelForCausalLM.from_pretrained("gpt2")

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

In [ ]:
input_ids

tensor([[   40, 14267,  1973,   262]])

In [ ]:
outputs = gpt2(input_ids)

In [ ]:
outputs.logits.shape

torch.Size([1, 4, 50257])

In [ ]:
outputs.logits

tensor([[[-39.3084, -39.0100, -41.8374,  ..., -46.9337, -44.9074, -39.5149],
         [-78.0579, -78.4766, -82.9907,  ..., -87.3914, -86.9835, -79.6007],
         [-73.0664, -74.0119, -78.5555,  ..., -81.0934, -82.5249, -75.8570],
         [-87.5486, -86.0567, -88.3320,  ..., -88.2509, -90.5480, -86.1209]]],
       grad_fn=<UnsafeViewBackward0>)

In [ ]:
final_logits = gpt2(input_ids).logits[0, -1]

In [ ]:
final_logits

tensor([-87.5486, -86.0567, -88.3320,  ..., -88.2509, -90.5480, -86.1209],
       grad_fn=<SelectBackward0>)

In [ ]:
final_logits.argmax() # Token ID <--> Index location Logits

tensor(1627)

In [ ]:
tokenizer.decode(final_logits.argmax())

' line'

In [ ]:
top10_logits = torch.topk(final_logits, 20)

In [ ]:
for index in top10_logits.indices:
    print(tokenizer.decode(index))

 line
 street
 river
 room
 pond
 bridge
 border
 country
 road
 board
 floor
 table
 world
 entire
 ocean
 whole
 streets
 field
 top
 lines


In [ ]:
sentence = "I like machine learning to be able to predict the future."
output = gpt2(tokenizer(sentence, return_tensors="pt").input_ids)
tokenizer.decode(output.logits[0, -1].argmax())

NameError: name 'gpt2' is not defined

In [ ]:
sentence = "I like shopping for things that are really good for you. I like to buy things that are"
output = gpt2(tokenizer(sentence, return_tensors="pt").input_ids)
tokenizer.decode(output.logits[0, -1].argmax())

' really'

In [ ]:
sentence = "I learn in university about machine learning and how to use it to improve your learning"
output = gpt2(tokenizer(sentence, return_tensors="pt").input_ids)
tokenizer.decode(output.logits[0, -1].argmax())

'.'

In [ ]:
sentence = "I like shopping with people who are like my"
output = gpt2(tokenizer(sentence, return_tensors="pt").input_ids)
final_logits = output.logits[0, -1]
tokenizer.decode(output.logits[0, -1].argmax())

top10_logits = torch.topk(final_logits, 10)
for index in top10_logits.indices:
    print(tokenizer.decode(index))

 family
 friends
 mom
 parents
 dad
 wife
 brother
 friend
 sister
 grandparents


In [ ]:
sentence = "I like shopping with people who are like my"
output = gpt2(tokenizer(sentence, return_tensors="pt").input_ids)
final_logits = output.logits[0, -1]
tokenizer.decode(output.logits[0, -1].argmax())

top10_logits = torch.topk(final_logits, 10)
for index in top10_logits.indices:
    print(tokenizer.decode(index))

 family
 friends
 mom
 parents
 dad
 wife
 brother
 friend
 sister
 grandparents


In [ ]:
import torch
import torch.nn.functional as F

# ---------------------------
# 1. Greedy Decoding (Argmax)
# ---------------------------
def greedy_decode(logits):
    """Return token index with maximum probability."""
    return torch.argmax(logits, dim=-1)


# ---------------------------
# 2. Top-k Sampling
# ---------------------------
def top_k_sampling(logits, k=50):
    """
    Keep only top-k logits, normalize them into probabilities,
    then sample one token from the filtered distribution.
    """
    values, indices = torch.topk(logits, k)
    probs = F.softmax(values, dim=-1)
    sampled = torch.multinomial(probs, 1)
    return indices[sampled]


# ---------------------------
# 3. Top-p (Nucleus) Sampling
# ---------------------------
def top_p_sampling(logits, p=0.9):
    """
    Sort tokens by probability, keep smallest number whose cumulative
    probability exceeds 'p', then sample one token.
    """
    sorted_logits, sorted_indices = torch.sort(logits, descending=True)
    sorted_probs = F.softmax(sorted_logits, dim=-1)
    cumulative_probs = sorted_probs.cumsum(dim=-1)

    # Mask tokens outside nucleus
    mask = cumulative_probs > p
    sorted_logits[mask] = float('-inf')

    # Sample from filtered logits
    filtered_probs = F.softmax(sorted_logits, dim=-1)
    sampled = torch.multinomial(filtered_probs, 1)

    # Return token index in original vocabulary
    return sorted_indices[sampled]


# ---------------------------
# 4. Temperature Sampling
# ---------------------------
def temperature_sampling(logits, temperature=1.0):
    """
    Scale logits by temperature before sampling.
    Lower temperature → sharper distribution.
    """
    scaled = logits / temperature
    probs = F.softmax(scaled, dim=-1)
    return torch.multinomial(probs, 1)


# ---------------------------
# 5. Random Sampling from Full Distribution
# ---------------------------
def random_sampling(logits):
    """
    Sample directly from softmax distribution without filtering.
    """
    probs = F.softmax(logits, dim=-1)
    return torch.multinomial(probs, 1)


# ---------------------------
# 6. Utility: Get Top-k Tokens for Display
# ---------------------------
def top_k_tokens(logits, tokenizer, k=10):
    values, indices = torch.topk(logits, k)
    return [(tokenizer.decode([idx]), float(values[i])) for i, idx in enumerate(indices)]


sentence = "Today I decided to go to the local mall and"
inputs = tokenizer(sentence, return_tensors="pt")
output = gpt2(**inputs)
logits = output.logits[0, -1]

print("Greedy:", tokenizer.decode([greedy_decode(logits)]))
print("Top-k:", tokenizer.decode(top_k_sampling(logits, k=10)))
print("Top-p:", tokenizer.decode(top_p_sampling(logits, p=0.9)))
print("Temp:", tokenizer.decode(temperature_sampling(logits, temperature=0.7)))
print("Random:", tokenizer.decode(random_sampling(logits)))
print(f"==============\n")

top10 = torch.topk(logits.softmax(dim=0), 10)
for value, index in zip(top10.values, top10.indices):
    print(f"{tokenizer.decode(index)} -- {value:.1%}")

Greedy:  buy
Top-k:  I
Top-p:  buy
Temp:  was
Random:  bought

 buy -- 23.4%
 bought -- 6.2%
 see -- 4.3%
 get -- 3.9%
 try -- 3.1%
 pick -- 3.0%
 purchase -- 2.7%
 check -- 2.6%
 I -- 2.6%
 find -- 2.5%


In [ ]:
final_logits.softmax(dim=0)

tensor([2.7841e-06, 1.6066e-05, 5.8392e-08,  ..., 4.2602e-06, 1.3941e-08,
        1.0811e-06], grad_fn=<SoftmaxBackward0>)

In [ ]:
top10 = torch.topk(final_logits.softmax(dim=0), 10)
top10

torch.return_types.topk(
values=tensor([0.1169, 0.0993, 0.0722, 0.0557, 0.0395, 0.0320, 0.0263, 0.0210, 0.0208,
        0.0193], grad_fn=<TopkBackward0>),
indices=tensor([ 1641,  2460,  1995,  3397,  9955,  3656,  3956,  1545,  6621, 28571]))

In [ ]:
for value, index in zip(top10.values, top10.indices):
    print(f"{tokenizer.decode(index)} -- {value.item():.1%}")

 family -- 11.7%
 friends -- 9.9%
 mom -- 7.2%
 parents -- 5.6%
 dad -- 3.9%
 wife -- 3.2%
 brother -- 2.6%
 friend -- 2.1%
 sister -- 2.1%
 grandparents -- 1.9%


In [ ]:
output_ids = gpt2.generate(input_ids, max_new_tokens=20)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.


In [ ]:
decoded_text = tokenizer.decode(output_ids[0])
decoded_text

'I skip across the line to the next section.\n\nThe first thing to note is that the first line is a'

In [ ]:
output_ids = gpt2.generate(input_ids, max_new_tokens=200)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [ ]:
print(tokenizer.decode(output_ids[0]))

I skip across the line to the next section.

The first thing to note is that the first line is a list of all the items in the list. This is a list of all the items in the list. The second line is a list of all the items in the list. This is a list of all the items in the list. The third line is a list of all the items in the list. This is a list of all the items in the list. The fourth line is a list of all the items in the list. This is a list of all the items in the list. The fifth line is a list of all the items in the list. This is a list of all the items in the list. The sixth line is a list of all the items in the list. This is a list of all the items in the list. The seventh line is a list of all the items in the list. This is a list of all the items in the list. The eighth line


In [ ]:
output_ids = gpt2.generate(input_ids, max_new_tokens=200, repetition_penalty=1.5, do_sample=True, top_k=5, top_p=0.94)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [ ]:
output_ids = gpt2.generate(input_ids, max_new_tokens=20, repetition_penalty=1.5, do_sample=True, temperature=0.5)

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


In [ ]:
decoded_text = tokenizer.decode(output_ids[0])

In [ ]:
print(decoded_text)

I skip across the line and go to a different part of town.

The next morning, I was in my


In [ ]:
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-generation", model="openai-community/gpt2")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0


In [ ]:
pipe("I went to the store and bought a")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': "I went to the store and bought a small backpack I bought for my mother. I went over the product and then went through the product and found out that it was a little different. I bought it for my sister and her sister also. She was a very young girl and I was very upset about that. But I didn't go over to the store and buy the product because she was so young and she didn't want to buy it.\n\nWe had a different family and we were told that they had to take care of the kids. I was just so upset. I'm so glad we found this stuff and then went to the store and bought it. It's amazing. It's very cool.\n\nWhat do you think of the new Hennepin County Sheriff's department?\n\nI'm in love with this department and I'm excited to be doing what I love doing. I'm looking forward to it.\n\nWhat did you think of the new sheriff's department?\n\nHe's a great guy. He's a gentleman. I think he's very smart and he's a good sheriff. It's going to be great for us. We've got a lot of new

In [ ]:
pipe("What is machine learning?")

Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.


[{'generated_text': 'What is machine learning?\n\nMachine learning is a process of taking data from a computer and combining it with other data. It is a process of finding and processing information in a way that is more similar to human vision. It is a process of creating a representation in a way that is more real than human vision. The process is called machine learning.\n\nHow does machine learning compare to human vision?\n\nMachine learning compares to human vision when it comes to looking at a visual world. We have the ability to determine the position of objects using the visual system. We can determine where objects are in the world. We can determine what they look like in the world.\n\nWhat are the challenges and challenges of machine learning?\n\nMachine learning is a process of processing information through the use of a computer. In our case, we are trying to find a way to make a better representation of the image in a computer. We are trying to find a way to make a better

In [ ]:
pipe(sentences)

[{'label': 'positive', 'score': 0.9434744715690613},
 {'label': 'negative', 'score': 0.9659876823425293}]

----------------------------------------------------------------------
----------------------------------------------------------------------
----------------------------------------------------------------------

## Sentiment Analysis

In [ ]:
from datasets import load_dataset

dataset = load_dataset("stanfordnlp/imdb")

README.md: 0.00B [00:00, ?B/s]

plain_text/train-00000-of-00001.parquet:   0%|          | 0.00/21.0M [00:00<?, ?B/s]

plain_text/test-00000-of-00001.parquet:   0%|          | 0.00/20.5M [00:00<?, ?B/s]

plain_text/unsupervised-00000-of-00001.p(…):   0%|          | 0.00/42.0M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/25000 [00:00<?, ? examples/s]

Generating unsupervised split:   0%|          | 0/50000 [00:00<?, ? examples/s]

In [ ]:
dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

In [ ]:
type(dataset)

datasets.dataset_dict.DatasetDict

In [ ]:
dataset["train"]

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

In [ ]:
help(dataset["train"])

Help on Dataset in module datasets.arrow_dataset object:

class Dataset(DatasetInfoMixin, datasets.search.IndexableMixin, TensorflowDatasetMixin)
 |  Dataset(arrow_table: datasets.table.Table, info: Optional[datasets.info.DatasetInfo] = None, split: Optional[datasets.splits.NamedSplit] = None, indices_table: Optional[datasets.table.Table] = None, fingerprint: Optional[str] = None)
 |
 |  A Dataset backed by an Arrow table.
 |
 |  Method resolution order:
 |      Dataset
 |      DatasetInfoMixin
 |      datasets.search.IndexableMixin
 |      TensorflowDatasetMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __del__(self)
 |
 |  __enter__(self)
 |
 |  __exit__(self, exc_type, exc_val, exc_tb)
 |
 |  __getitem__(self, key)
 |      Can be used to index columns (by string names) or rows (by integer index or iterable of indices or bools).
 |
 |  __getitems__(self, keys: list) -> list
 |      Can be used to get a batch using a list of integers indices.
 |
 |  __init__(self, ar

In [ ]:
dataset["train"].to_pandas()

,text,label
0,I rented I AM CURIOUS-YELLOW from my video sto...,0
1,"""I Am Curious: Yellow"" is a risible and preten...",0
2,If only to avoid making this type of film in t...,0
3,This film was probably inspired by Godard's Ma...,0
4,"Oh, brother...after hearing about this ridicul...",0
...,...,...
24995,A hit at the time but now better categorised a...,1
24996,I love this movie like no other. Another time ...,1
24997,This film and it's sequel Barry Mckenzie holds...,1
24998,'The Adventures Of Barry McKenzie' started lif...,1


In [ ]:
dataset["train"].to_pandas()["text"]

,text
0,I rented I AM CURIOUS-YELLOW from my video sto...
1,"""I Am Curious: Yellow"" is a risible and preten..."
2,If only to avoid making this type of film in t...
3,This film was probably inspired by Godard's Ma...
4,"Oh, brother...after hearing about this ridicul..."
...,...
24995,A hit at the time but now better categorised a...
24996,I love this movie like no other. Another time ...
24997,This film and it's sequel Barry Mckenzie holds...
24998,'The Adventures Of Barry McKenzie' started lif...


In [ ]:
from transformers import pipeline

In [ ]:
pipe = pipeline("sentiment-analysis")

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cuda:0


In [ ]:
dataset_df = dataset["train"].to_pandas()
dataset_df

,text,label
0,I rented I AM CURIOUS-YELLOW from my video sto...,0
1,"""I Am Curious: Yellow"" is a risible and preten...",0
2,If only to avoid making this type of film in t...,0
3,This film was probably inspired by Godard's Ma...,0
4,"Oh, brother...after hearing about this ridicul...",0
...,...,...
24995,A hit at the time but now better categorised a...,1
24996,I love this movie like no other. Another time ...,1
24997,This film and it's sequel Barry Mckenzie holds...,1
24998,'The Adventures Of Barry McKenzie' started lif...,1


In [ ]:
pipe(dataset_df["text"].iloc[1])

[{'label': 'NEGATIVE', 'score': 0.9991909861564636}]

In [ ]:
def score(review_text):
    return pipe(review_text[:500])[0]["label"]

In [ ]:
dataset_df["model_prediction"] = dataset_df["text"].apply(score)

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset


In [ ]:
dataset_df

,text,label,model_prediction
0,I rented I AM CURIOUS-YELLOW from my video sto...,0,NEGATIVE
1,"""I Am Curious: Yellow"" is a risible and preten...",0,NEGATIVE
2,If only to avoid making this type of film in t...,0,NEGATIVE
3,This film was probably inspired by Godard's Ma...,0,POSITIVE
4,"Oh, brother...after hearing about this ridicul...",0,NEGATIVE
...,...,...,...
24995,A hit at the time but now better categorised a...,1,NEGATIVE
24996,I love this movie like no other. Another time ...,1,POSITIVE
24997,This film and it's sequel Barry Mckenzie holds...,1,POSITIVE
24998,'The Adventures Of Barry McKenzie' started lif...,1,NEGATIVE


In [ ]:
from datasets import load_dataset

reviews = load_dataset("rotten_tomatoes")

README.md: 0.00B [00:00, ?B/s]

train.parquet:   0%|          | 0.00/699k [00:00<?, ?B/s]

validation.parquet:   0%|          | 0.00/90.0k [00:00<?, ?B/s]

test.parquet:   0%|          | 0.00/92.2k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/8530 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1066 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1066 [00:00<?, ? examples/s]

In [ ]:
pipe = pipeline(task="text-classification", model="ProsusAI/finbert")

config.json:   0%|          | 0.00/758 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cuda:0


In [ ]:
pipe("The company reported a strong increase in quarterly revenue, exceeding market expectations.")

[{'label': 'positive', 'score': 0.9543071389198303}]

In [ ]:
pipe("Shares fell after the firm reported lower-than-expected earnings")

[{'label': 'negative', 'score': 0.9718543887138367}]

In [ ]:
sentences = ["Strong consumer demand drove record sales across all regions",
             "Supply chain disruptions severely affected production output."]

## Named Entity Recognition (My Example)

In [ ]:
sentence = "Apple announced record earnings in the United States on Monday"

In [ ]:
ner_tag_pipe = pipeline("ner")

No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496 (https://huggingface.co/dbmdz/bert-large-cased-finetuned-conll03-english).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Some weights of the model checkpoint at dbmdz/bert-large-cased-finetuned-conll03-english were not used when initializing BertForTokenClassification: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight']
- This IS expected if you are initializing BertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Device set to use cuda:0


In [ ]:
ner_tag_pipe(sentence)

[{'entity': 'I-ORG',
  'score': np.float32(0.99911004),
  'index': 1,
  'word': 'Apple',
  'start': 0,
  'end': 5},
 {'entity': 'I-LOC',
  'score': np.float32(0.99967754),
  'index': 7,
  'word': 'United',
  'start': 39,
  'end': 45},
 {'entity': 'I-LOC',
  'score': np.float32(0.9996001),
  'index': 8,
  'word': 'States',
  'start': 46,
  'end': 52}]

In [ ]:
ner_tag_pipe("Amazon expanded its logistics operations in Germany")

[{'entity': 'I-ORG',
  'score': np.float32(0.99928266),
  'index': 1,
  'word': 'Amazon',
  'start': 0,
  'end': 6},
 {'entity': 'I-LOC',
  'score': np.float32(0.999806),
  'index': 7,
  'word': 'Germany',
  'start': 44,
  'end': 51}]

----------------------------------------------------------------------
----------------------------------------------------------------------
----------------------------------------------------------------------

## Question Answering

In [ ]:
qa_bot = pipeline("question-answering")

No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 564e9b5 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0


In [ ]:
my_text = """
السماء لونها ازرق
"""

qa_bot(question="ما لون السماء", context=my_text)

{'score': 0.2881357427686453, 'start': 8, 'end': 18, 'answer': 'لونها ازرق'}

In [ ]:
text = """
The expansion began shortly after 2015 with rapid advances in deep learning and
large-scale data availability, driven by breakthroughs in neural network
architectures and GPU acceleration. The early phase of growth was marked by
significant investment from technology companies and research institutions,
alongside the deployment of AI systems in speech recognition, computer vision,
and recommendation engines. By the late 2010s, large-scale language models and
cloud-based AI services had emerged as central pillars of the industry.
The global AI ecosystem was divided into several major sectors: machine learning
 platforms, natural language processing, computer vision, autonomous systems,
 and AI-driven analytics. Competitive pressure accelerated innovation,
 particularly in foundation models and infrastructure, with companies racing
 to scale model size and efficiency. Regulatory scrutiny and ethical
 considerations began to shape deployment strategies, especially in
 healthcare, finance, and public services.
"""

In [ ]:
question = "When did the major expansion of the AI industry begin?"

In [ ]:
result = qa_bot(question=question, context=text)
result

{'score': 0.4866883456707001,
 'start': 21,
 'end': 39,
 'answer': 'shortly after 2015'}

In [ ]:
question = "What technological advances drove the early growth of the AI industry?"

In [ ]:
result = qa_bot(question=question, context=text)
result

{'score': 0.38779252767562866,
 'start': 122,
 'end': 188,
 'answer': 'breakthroughs in neural network\narchitectures and GPU acceleration'}

In [ ]:
text[122:188]

'breakthroughs in neural network\narchitectures and GPU acceleration'

In [ ]:
print(result["answer"])

breakthroughs in neural network
architectures and GPU acceleration


In [ ]:
my_text_knowledge = """
The sky is blue and pure. The earth has diversified geologicial details.
"""

In [ ]:
question = "What is the color of the sky"

qa_bot(question=question, context=my_text_knowledge)

{'score': 0.4470493197441101,
 'start': 12,
 'end': 25,
 'answer': 'blue and pure'}

### Electra Model For RAG Tasks

In [ ]:
# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("question-answering", model="ahotrod/electra_large_discriminator_squad2_512")

Device set to use cuda:0


In [ ]:
text = """
The expansion began shortly after 2015 with rapid advances in deep learning and
large-scale data availability, driven by breakthroughs in neural network
architectures and GPU acceleration. The early phase of growth was marked by
significant investment from technology companies and research institutions,
alongside the deployment of AI systems in speech recognition, computer vision,
and recommendation engines. By the late 2010s, large-scale language models and
cloud-based AI services had emerged as central pillars of the industry.
The global AI ecosystem was divided into several major sectors: machine learning
 platforms, natural language processing, computer vision, autonomous systems,
 and AI-driven analytics. Competitive pressure accelerated innovation,
 particularly in foundation models and infrastructure, with companies racing
 to scale model size and efficiency. Regulatory scrutiny and ethical
 considerations began to shape deployment strategies, especially in
 healthcare, finance, and public services.
"""

question = "What are the breakthroughs that made AI possible?"

print(qa_bot(question=question, context=text)["answer"])

neural network
architectures and GPU acceleration


----------------------------------------------------------------------
----------------------------------------------------------------------
----------------------------------------------------------------------


## Machine Translation

In [ ]:
translate = pipeline("translation_en_to_fr")

No model was supplied, defaulted to google-t5/t5-base and revision a9723ea (https://huggingface.co/google-t5/t5-base).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Device set to use cuda:0


In [ ]:
translate("Hello")

[{'translation_text': 'Bonjour'}]

In [ ]:
translate("Thanks")

[{'translation_text': 'Merci'}]

In [ ]:
translate("Artificial intelligence is transforming many industries around the world")

[{'translation_text': "L'intelligence artificielle transforme de nombreuses industries dans le monde"}]

----------------------------------------------------------------------
----------------------------------------------------------------------
----------------------------------------------------------------------

